$axure.loadCurrentPage({
  "url":"职位发布.html",
  "generationDate":new Date(1445572059626.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"71640d4e6d2a455ba16d772a08e467c6",
    "type":"Axure:Page",
    "name":"职位发布",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4cbdc3f40ab6421b82f435c760f8edd7",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"6da809df75bc435e9f8f821d61e292cb"},
{
          "id":"a29a7f7209e34156912d061f80e55ed1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":110},
            "size":{
              "width":200,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb4da4dc337e4e67977bcc5d577398bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":110},
                "size":{
                  "width":200,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/职位发布/u17.png"}},
{
          "id":"34fe76961f1c451d8fe5fe19f1de4dbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":280,
              "y":110},
            "size":{
              "width":760,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e672dabcde0406792502412458d9a1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":280,
                  "y":110},
                "size":{
                  "width":760,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/职位发布/u19.png"}},
{
          "id":"7a06f3a3bf724953b8ea69aeead70968",
          "label":"搜索框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":297,
              "y":117},
            "size":{
              "width":514,
              "height":45}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入关键字搜索"},
{
          "id":"d018bf3554934098b2e3e98df36866c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":832,
              "y":117},
            "size":{
              "width":193,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba6ed4ff64fa491097214139c8c1d37c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":832,
                  "y":117},
                "size":{
                  "width":193,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/职位发布/u22.png"}},
{
          "id":"840111b0226b4facb0294e09be5c0fdf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":862,
              "y":121},
            "size":{
              "width":48,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0b4e7f4b85241d983ff87c78754ec80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":862,
                  "y":121},
                "size":{
                  "width":48,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/职位发布/u24.png"}},
{
          "id":"1f8ee18ba0154030ab29c85167b6aede",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":250},
            "size":{
              "width":200,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17a926d2133a4096abb476e1e6f9584b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":250},
                "size":{
                  "width":200,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/职位发布/u26.png"}},
{
          "id":"fa72c9995ee0463b997c2ef339082032",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":380},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36e6cd8ea2184d228c076c39ed590128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":380},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/职位发布/u28.png"}},
{
          "id":"d3041334a8b442869554ef546631b29f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":500},
            "size":{
              "width":200,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64e88309e2b44643a60c4676c85272a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":500},
                "size":{
                  "width":200,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/职位发布/u26.png"}},
{
          "id":"eb3e68013b3d408a8311b59a76fb33cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":180},
            "size":{
              "width":760,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bab86ad7a824a44b5e07dd8eb084b4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":180},
                "size":{
                  "width":760,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/职位发布/u32.png"}},
{
          "id":"6b38829b87014eea99ad7a59459b96f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":240},
            "size":{
              "width":770,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"672e5933c1bf4707b9a43f7bbe064e7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":240},
                "size":{
                  "width":770,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/职位发布/u34.png"}},
{
          "id":"00840d2570db46d7a7fdba88c2e9ff16",
          "label":"neirong",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":240},
            "size":{
              "width":750,
              "height":370}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4c34333a950147a9a95165ba212f293b",
              "label":"item1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f54433679f1542a1a228744dd3d9b595",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":310},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6dc38a2daac941cebb55dabaded10891",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":310},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u89.png"}},
{
                  "id":"c3c4873aeae741c0afd869d3085ca482",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":90,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0431c83465834f3ea80d03689a8a12eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":90,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u91.png"}},
{
                  "id":"d511192e98b64b64a0f642c1aff98faf",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":158,
                      "y":24},
                    "size":{
                      "width":112,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"80aa0120ca124b74a3332cf397ad51e5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":158,
                          "y":24},
                        "size":{
                          "width":112,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5627ff1e133d4a8ebf959009eebf2342",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":348,
                      "y":27},
                    "size":{
                      "width":112,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e03cb99100334ea4b9d07a2c33e5e95b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":348,
                          "y":27},
                        "size":{
                          "width":112,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c6a391cb10f8408d883bb79d6e470928",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":508,
                      "y":27},
                    "size":{
                      "width":112,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fc9b92371f124379a9a30802b50638a5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":508,
                          "y":27},
                        "size":{
                          "width":112,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"377fb16368a5470e9bc7b54178c7b47f",
                  "label":"秒",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"right",
                    "location":{
                      "x":689,
                      "y":20},
                    "size":{
                      "width":27,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"285eb9b3451e4032a8a16e928e6d1b7a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"right",
                        "location":{
                          "x":689,
                          "y":20},
                        "size":{
                          "width":27,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"208127b1f0fe450d925e2d7a5f74f5a1",
                  "label":"分",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"right",
                    "location":{
                      "x":648,
                      "y":20},
                    "size":{
                      "width":27,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d41857ec2e014880bb4ef90e66870a1f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"right",
                        "location":{
                          "x":648,
                          "y":20},
                        "size":{
                          "width":27,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"02cc68b8b0db4f90b41e36ad36609f38",
                  "label":"时",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"right",
                    "location":{
                      "x":607,
                      "y":20},
                    "size":{
                      "width":27,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfaa72a663394ffaa6e596804adcc1fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"right",
                        "location":{
                          "x":607,
                          "y":20},
                        "size":{
                          "width":27,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"173fe61a9af14761858e4a7cfac562fe",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "location":{
                      "x":621,
                      "y":22},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a2dbce82d7b4961996f69c8aad81664",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"right",
                        "location":{
                          "x":621,
                          "y":22},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"06cdfd5dd7d144759d3e720758d76913",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "location":{
                      "x":662,
                      "y":22},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c312d0aad13f408b9bf4fc70754cce83",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"right",
                        "location":{
                          "x":662,
                          "y":22},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dda1b31f934b423d897200d8a92cf97e",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "location":{
                      "x":703,
                      "y":20},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"82d72ab9044e4e24b5317243a9d2a730",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"right",
                        "location":{
                          "x":703,
                          "y":20},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"787c4b9e40cb4bbb966c00a86539a26e",
                  "label":"loop",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":600,
                      "y":10},
                    "size":{
                      "width":1,
                      "height":1}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onPanelStateChange":{
                      "description":"OnPanelStateChange",
                      "cases":[{
                          "description":"用例 1<br> (If 文字于 秒 &gt; &quot;0&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":">",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["377fb16368a5470e9bc7b54178c7b47f"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]}},
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 秒 = &quot;[[LVAR1-1]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["377fb16368a5470e9bc7b54178c7b47f"]},
{
                                        "exprType":"htmlLiteral",
                                        "value":"<p style=\"font-size:20px;text-align:right;line-height:normal;\"><span style=\"font-family:'Arial Normal', 'Arial';font-weight:400;font-style:normal;font-size:20px;color:#333333;text-align:right;line-height:normal;\">[[LVAR1-1]]</span></p>",
                                        "localVariables":{
                                          "lvar1":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["377fb16368a5470e9bc7b54178c7b47f"]}]}},
                                        "stos":[{
                                            "computedType":"int",
                                            "sto":"binOp",
                                            "op":"-",
                                            "leftSTO":{
                                              "sto":"var",
                                              "name":"lvar1"},
                                            "rightSTO":{
                                              "computedType":"int",
                                              "sto":"literal",
                                              "value":1}}]},
{
                                        "exprType":"booleanLiteral",
                                        "value":false}]}]}}]},
{
                          "description":"用例 1<br> (Else If 文字于 分 &gt; &quot;0&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":">",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["208127b1f0fe450d925e2d7a5f74f5a1"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]}},
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 分 = &quot;[[LVAR1-1]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["208127b1f0fe450d925e2d7a5f74f5a1"]},
{
                                        "exprType":"htmlLiteral",
                                        "value":"<p style=\"font-size:20px;text-align:right;line-height:normal;\"><span style=\"font-family:'Arial Normal', 'Arial';font-weight:400;font-style:normal;font-size:20px;color:#333333;text-align:right;line-height:normal;\">[[LVAR1-1]]</span></p>",
                                        "localVariables":{
                                          "lvar1":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["208127b1f0fe450d925e2d7a5f74f5a1"]}]}},
                                        "stos":[{
                                            "computedType":"int",
                                            "sto":"binOp",
                                            "op":"-",
                                            "leftSTO":{
                                              "sto":"var",
                                              "name":"lvar1"},
                                            "rightSTO":{
                                              "computedType":"int",
                                              "sto":"literal",
                                              "value":1}}]},
{
                                        "exprType":"booleanLiteral",
                                        "value":false}]}]}},
{
                              "action":"setFunction",
                              "description":"设置 文字于 秒 = &quot;59&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["377fb16368a5470e9bc7b54178c7b47f"]},
{
                                        "exprType":"htmlLiteral",
                                        "value":"<p style=\"font-size:20px;text-align:right;line-height:normal;\"><span style=\"font-family:'Arial Normal', 'Arial';font-weight:400;font-style:normal;font-size:20px;color:#333333;text-align:right;line-height:normal;\">59</span></p>",
                                        "localVariables":{
},
                                        "stos":[]},
{
                                        "exprType":"booleanLiteral",
                                        "value":false}]}]}}]},
{
                          "description":"用例 1<br> (Else If 文字于 时 &gt; &quot;0&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":">",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["02cc68b8b0db4f90b41e36ad36609f38"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]}},
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 时 = &quot;[[LVAR1-1]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["02cc68b8b0db4f90b41e36ad36609f38"]},
{
                                        "exprType":"htmlLiteral",
                                        "value":"<p style=\"font-size:20px;text-align:right;line-height:normal;\"><span style=\"font-family:'Arial Normal', 'Arial';font-weight:400;font-style:normal;font-size:20px;color:#333333;text-align:right;line-height:normal;\">[[LVAR1-1]]</span></p>",
                                        "localVariables":{
                                          "lvar1":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["02cc68b8b0db4f90b41e36ad36609f38"]}]}},
                                        "stos":[{
                                            "computedType":"int",
                                            "sto":"binOp",
                                            "op":"-",
                                            "leftSTO":{
                                              "sto":"var",
                                              "name":"lvar1"},
                                            "rightSTO":{
                                              "computedType":"int",
                                              "sto":"literal",
                                              "value":1}}]},
{
                                        "exprType":"booleanLiteral",
                                        "value":false}]}]}},
{
                              "action":"setFunction",
                              "description":"设置 文字于 分 = &quot;59&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["208127b1f0fe450d925e2d7a5f74f5a1"]},
{
                                        "exprType":"htmlLiteral",
                                        "value":"<p style=\"font-size:20px;text-align:right;line-height:normal;\"><span style=\"font-family:'Arial Normal', 'Arial';font-weight:400;font-style:normal;font-size:20px;color:#333333;text-align:right;line-height:normal;\">59</span></p>",
                                        "localVariables":{
},
                                        "stos":[]},
{
                                        "exprType":"booleanLiteral",
                                        "value":false}]}]}},
{
                              "action":"setFunction",
                              "description":"设置 文字于 秒 = &quot;59&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["377fb16368a5470e9bc7b54178c7b47f"]},
{
                                        "exprType":"htmlLiteral",
                                        "value":"<p style=\"font-size:20px;text-align:right;line-height:normal;\"><span style=\"font-family:'Arial Normal', 'Arial';font-weight:400;font-style:normal;font-size:20px;color:#333333;text-align:right;line-height:normal;\">59</span></p>",
                                        "localVariables":{
},
                                        "stos":[]},
{
                                        "exprType":"booleanLiteral",
                                        "value":false}]}]}}]},
{
                          "description":"用例 2<br> (If &quot;[[LVAR1.length]]&quot; &lt; &quot;2&quot;)",
                          "isNewIfGroup":true,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"<",
                            "leftExpr":{
                              "exprType":"stringLiteral",
                              "value":"[[LVAR1.length]]",
                              "localVariables":{
                                "lvar1":{
                                  "exprType":"fcall",
                                  "functionName":"GetWidgetText",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["377fb16368a5470e9bc7b54178c7b47f"]}]}},
                              "stos":[{
                                  "computedType":"int",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"string",
                                    "sto":"var",
                                    "name":"lvar1"},
                                  "prop":"length"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"2",
                              "stos":[]}},
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 秒 = &quot;0[[LVAR1]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["377fb16368a5470e9bc7b54178c7b47f"]},
{
                                        "exprType":"htmlLiteral",
                                        "value":"<p style=\"font-size:20px;text-align:right;line-height:normal;\"><span style=\"font-family:'Arial Normal', 'Arial';font-weight:400;font-style:normal;font-size:20px;color:#333333;text-align:right;line-height:normal;\">0</span><span style=\"font-family:'Arial Normal', 'Arial';font-weight:400;font-style:normal;font-size:20px;color:#333333;text-align:right;line-height:normal;\">[[LVAR1]]</span></p>",
                                        "localVariables":{
                                          "lvar1":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["377fb16368a5470e9bc7b54178c7b47f"]}]}},
                                        "stos":[{
                                            "sto":"var",
                                            "name":"lvar1"}]},
{
                                        "exprType":"booleanLiteral",
                                        "value":false}]}]}}]},
{
                          "description":"用例 2<br> (If &quot;[[LVAR1.length]]&quot; &lt; &quot;2&quot;)",
                          "isNewIfGroup":true,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"<",
                            "leftExpr":{
                              "exprType":"stringLiteral",
                              "value":"[[LVAR1.length]]",
                              "localVariables":{
                                "lvar1":{
                                  "exprType":"fcall",
                                  "functionName":"GetWidgetText",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["208127b1f0fe450d925e2d7a5f74f5a1"]}]}},
                              "stos":[{
                                  "computedType":"int",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"string",
                                    "sto":"var",
                                    "name":"lvar1"},
                                  "prop":"length"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"2",
                              "stos":[]}},
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 分 = &quot;0[[LVAR1]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["208127b1f0fe450d925e2d7a5f74f5a1"]},
{
                                        "exprType":"htmlLiteral",
                                        "value":"<p style=\"font-size:20px;text-align:right;line-height:normal;\"><span style=\"font-family:'Arial Normal', 'Arial';font-weight:400;font-style:normal;font-size:20px;color:#333333;text-align:right;line-height:normal;\">0[[LVAR1]]</span></p>",
                                        "localVariables":{
                                          "lvar1":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["208127b1f0fe450d925e2d7a5f74f5a1"]}]}},
                                        "stos":[{
                                            "sto":"var",
                                            "name":"lvar1"}]},
{
                                        "exprType":"booleanLiteral",
                                        "value":false}]}]}}]},
{
                          "description":"用例 2<br> (If &quot;[[LVAR1.length]]&quot; &lt; &quot;2&quot;)",
                          "isNewIfGroup":true,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"<",
                            "leftExpr":{
                              "exprType":"stringLiteral",
                              "value":"[[LVAR1.length]]",
                              "localVariables":{
                                "lvar1":{
                                  "exprType":"fcall",
                                  "functionName":"GetWidgetText",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["02cc68b8b0db4f90b41e36ad36609f38"]}]}},
                              "stos":[{
                                  "computedType":"int",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"string",
                                    "sto":"var",
                                    "name":"lvar1"},
                                  "prop":"length"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"2",
                              "stos":[]}},
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 时 = &quot;0[[LVAR1]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["02cc68b8b0db4f90b41e36ad36609f38"]},
{
                                        "exprType":"htmlLiteral",
                                        "value":"<p style=\"font-size:20px;text-align:right;line-height:normal;\"><span style=\"font-family:'Arial Normal', 'Arial';font-weight:400;font-style:normal;font-size:20px;color:#333333;text-align:right;line-height:normal;\">0</span><span style=\"font-family:'Arial Normal', 'Arial';font-weight:400;font-style:normal;font-size:20px;color:#333333;text-align:right;line-height:normal;\">[[LVAR1]]</span></p>",
                                        "localVariables":{
                                          "lvar1":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["02cc68b8b0db4f90b41e36ad36609f38"]}]}},
                                        "stos":[{
                                            "sto":"var",
                                            "name":"lvar1"}]},
{
                                        "exprType":"booleanLiteral",
                                        "value":false}]}]}}]}]},
                    "onLoad":{
                      "description":"OnLoad",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 This to 下一步 wrap repeat every 1000 ms",
                              "panelsToStates":[{
                                  "panelPath":["787c4b9e40cb4bbb966c00a86539a26e"],
                                  "stateInfo":{
                                    "setStateType":"next",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":true,
                                    "showWhenSet":false,
                                    "repeat":1000,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"b0eb5582280145a2a77ee305e8dd6b0c",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[]},
{
                      "id":"a7e5b820653e44db89acd171244f2196",
                      "label":"状态2",
                      "type":"Axure:PanelDiagram",
                      "objects":[]}]},
{
                  "id":"e0fe0c891f56412a94c981e619d729d9",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":100},
                    "size":{
                      "width":90,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"07db178763ec488fbb88dfda9d93427c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":100},
                        "size":{
                          "width":90,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u91.png"}},
{
                  "id":"ed44e94b54584dfab394aa2a12b8eb89",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":158,
                      "y":114},
                    "size":{
                      "width":112,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e998a82e35846faa58dc68cf65459e9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":158,
                          "y":114},
                        "size":{
                          "width":112,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"774757e495c74613adaf17942514b029",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":348,
                      "y":117},
                    "size":{
                      "width":112,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dee23cf9f8904e339fcefaab946c6c62",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":348,
                          "y":117},
                        "size":{
                          "width":112,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dda17a519b2f40a587e882891c53fd34",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":508,
                      "y":117},
                    "size":{
                      "width":112,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2fdc93ca094f4b7ab2356bbaf163c77b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":508,
                          "y":117},
                        "size":{
                          "width":112,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a597f8728f414feea489342dac3367ee",
                  "label":"秒",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"right",
                    "location":{
                      "x":689,
                      "y":110},
                    "size":{
                      "width":27,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cb9e8f642a724d21bf5f7a6997c0c6b2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"right",
                        "location":{
                          "x":689,
                          "y":110},
                        "size":{
                          "width":27,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1ed45b3970cf4990af4fb20aabde02e7",
                  "label":"时",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"right",
                    "location":{
                      "x":607,
                      "y":110},
                    "size":{
                      "width":27,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0572839a8a484f76a2e68df640ee4d4f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"right",
                        "location":{
                          "x":607,
                          "y":110},
                        "size":{
                          "width":27,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f1dd187b2e1c495188a85f2a0b52e5fd",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "location":{
                      "x":621,
                      "y":112},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"02731b3162354b098c0f0cfd4f5e66ff",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"right",
                        "location":{
                          "x":621,
                          "y":112},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"824b27640b5b4f709431cd70861e512c",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "location":{
                      "x":662,
                      "y":112},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ba5e9e69f744e49a54057567ce95514",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"right",
                        "location":{
                          "x":662,
                          "y":112},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"22bb05691bb3451f9a382929f4c3904b",
                  "label":"",
                  "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "location":{
                      "x":703,
                      "y":110},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c43b165ca7fc47b79b2a10c8d80bc461",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00840d2570db46d7a7fdba88c2e9ff16",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"right",
                        "location":{
                          "x":703,
                          "y":110},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"f6985bbd083c405b9d7b4fc24a12c574",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":610}},
          "adaptiveStyles":{
},
          "masterId":"8c817e2d85e64062b1846487b39e3063"}]}},
  "masters":{
    "6da809df75bc435e9f8f821d61e292cb":{
      "packageId":"6da809df75bc435e9f8f821d61e292cb",
      "type":"Axure:Master",
      "name":"页头",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"43c546d8915a4321b512e7f804b4b31e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a571167ed7224235a7198a8e4f110359",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u36.png"}},
{
            "id":"344dc1ea6f2b4a21a32f6157e7d79490",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":270,
                "y":0},
              "size":{
                "width":760,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4f095b0f21fd474a8ae783872f7d0aa0",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":760,
                    "height":50}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"15aa05ddc18e4905a7f91554614b1d1c",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":152,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62c4a66a4a6444fc8f9a66f70b72a3d7",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":152,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u40.png"}},
{
                    "id":"1e69bb34e50f41c2af0f4dc7999fe314",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":152,
                        "y":0},
                      "size":{
                        "width":152,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b4759a9621f1461f8979fd2955fb02f8",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":152,
                            "y":0},
                          "size":{
                            "width":152,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u40.png"}},
{
                    "id":"03a69b3e980849a6ad5ca77cf0a1a8ea",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":304,
                        "y":0},
                      "size":{
                        "width":151,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"34c59e722b7f4be6b3af43cb54a952b9",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":304,
                            "y":0},
                          "size":{
                            "width":151,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u44.png"}},
{
                    "id":"d95ac2c22e17453abbbc15cc449fdc87",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":690,
                        "y":0},
                      "size":{
                        "width":70,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"355cd0edf55240c4b0f391064d5ee483",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":690,
                            "y":0},
                          "size":{
                            "width":70,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u50.png"}},
{
                    "id":"4e46d7c13faf4dd998d38f2224d68a2c",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":628,
                        "y":0},
                      "size":{
                        "width":62,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"afc52319c03c4ca9acc862e980dc028f",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":628,
                            "y":0},
                          "size":{
                            "width":62,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u48.png"}},
{
                    "id":"a06282ff864e40c58625fdf5dd2852ff",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":455,
                        "y":0},
                      "size":{
                        "width":173,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"ed32fc37c7604284a760b3588a9f1915",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":455,
                            "y":0},
                          "size":{
                            "width":173,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u46.png"}}]}]}]}},
    "8c817e2d85e64062b1846487b39e3063":{
      "packageId":"8c817e2d85e64062b1846487b39e3063",
      "type":"Axure:Master",
      "name":"页脚",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"bb20356460e0412d90c0916eb480f8c4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF000000},
              "size":{
                "width":970,
                "height":96},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b8218fa4a67e4e22be88537ce99d344e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF000000},
                  "size":{
                    "width":970,
                    "height":96},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u137.png"}}]}}},
  "objectPaths":{
    "4cbdc3f40ab6421b82f435c760f8edd7":{
      "scriptId":"u0",
      "43c546d8915a4321b512e7f804b4b31e":{
        "scriptId":"u1"},
      "a571167ed7224235a7198a8e4f110359":{
        "scriptId":"u2"},
      "344dc1ea6f2b4a21a32f6157e7d79490":{
        "scriptId":"u3"},
      "4f095b0f21fd474a8ae783872f7d0aa0":{
        "scriptId":"u4"},
      "15aa05ddc18e4905a7f91554614b1d1c":{
        "scriptId":"u5"},
      "62c4a66a4a6444fc8f9a66f70b72a3d7":{
        "scriptId":"u6"},
      "1e69bb34e50f41c2af0f4dc7999fe314":{
        "scriptId":"u7"},
      "b4759a9621f1461f8979fd2955fb02f8":{
        "scriptId":"u8"},
      "03a69b3e980849a6ad5ca77cf0a1a8ea":{
        "scriptId":"u9"},
      "34c59e722b7f4be6b3af43cb54a952b9":{
        "scriptId":"u10"},
      "a06282ff864e40c58625fdf5dd2852ff":{
        "scriptId":"u11"},
      "ed32fc37c7604284a760b3588a9f1915":{
        "scriptId":"u12"},
      "4e46d7c13faf4dd998d38f2224d68a2c":{
        "scriptId":"u13"},
      "afc52319c03c4ca9acc862e980dc028f":{
        "scriptId":"u14"},
      "d95ac2c22e17453abbbc15cc449fdc87":{
        "scriptId":"u15"},
      "355cd0edf55240c4b0f391064d5ee483":{
        "scriptId":"u16"}},
    "a29a7f7209e34156912d061f80e55ed1":{
      "scriptId":"u17"},
    "cb4da4dc337e4e67977bcc5d577398bc":{
      "scriptId":"u18"},
    "34fe76961f1c451d8fe5fe19f1de4dbf":{
      "scriptId":"u19"},
    "9e672dabcde0406792502412458d9a1b":{
      "scriptId":"u20"},
    "7a06f3a3bf724953b8ea69aeead70968":{
      "scriptId":"u21"},
    "d018bf3554934098b2e3e98df36866c8":{
      "scriptId":"u22"},
    "ba6ed4ff64fa491097214139c8c1d37c":{
      "scriptId":"u23"},
    "840111b0226b4facb0294e09be5c0fdf":{
      "scriptId":"u24"},
    "a0b4e7f4b85241d983ff87c78754ec80":{
      "scriptId":"u25"},
    "1f8ee18ba0154030ab29c85167b6aede":{
      "scriptId":"u26"},
    "17a926d2133a4096abb476e1e6f9584b":{
      "scriptId":"u27"},
    "fa72c9995ee0463b997c2ef339082032":{
      "scriptId":"u28"},
    "36e6cd8ea2184d228c076c39ed590128":{
      "scriptId":"u29"},
    "d3041334a8b442869554ef546631b29f":{
      "scriptId":"u30"},
    "64e88309e2b44643a60c4676c85272a1":{
      "scriptId":"u31"},
    "eb3e68013b3d408a8311b59a76fb33cb":{
      "scriptId":"u32"},
    "8bab86ad7a824a44b5e07dd8eb084b4f":{
      "scriptId":"u33"},
    "6b38829b87014eea99ad7a59459b96f7":{
      "scriptId":"u34"},
    "672e5933c1bf4707b9a43f7bbe064e7a":{
      "scriptId":"u35"},
    "00840d2570db46d7a7fdba88c2e9ff16":{
      "scriptId":"u36"},
    "f54433679f1542a1a228744dd3d9b595":{
      "scriptId":"u37"},
    "6dc38a2daac941cebb55dabaded10891":{
      "scriptId":"u38"},
    "c3c4873aeae741c0afd869d3085ca482":{
      "scriptId":"u39"},
    "0431c83465834f3ea80d03689a8a12eb":{
      "scriptId":"u40"},
    "d511192e98b64b64a0f642c1aff98faf":{
      "scriptId":"u41"},
    "80aa0120ca124b74a3332cf397ad51e5":{
      "scriptId":"u42"},
    "5627ff1e133d4a8ebf959009eebf2342":{
      "scriptId":"u43"},
    "e03cb99100334ea4b9d07a2c33e5e95b":{
      "scriptId":"u44"},
    "c6a391cb10f8408d883bb79d6e470928":{
      "scriptId":"u45"},
    "fc9b92371f124379a9a30802b50638a5":{
      "scriptId":"u46"},
    "377fb16368a5470e9bc7b54178c7b47f":{
      "scriptId":"u47"},
    "285eb9b3451e4032a8a16e928e6d1b7a":{
      "scriptId":"u48"},
    "208127b1f0fe450d925e2d7a5f74f5a1":{
      "scriptId":"u49"},
    "d41857ec2e014880bb4ef90e66870a1f":{
      "scriptId":"u50"},
    "02cc68b8b0db4f90b41e36ad36609f38":{
      "scriptId":"u51"},
    "bfaa72a663394ffaa6e596804adcc1fe":{
      "scriptId":"u52"},
    "173fe61a9af14761858e4a7cfac562fe":{
      "scriptId":"u53"},
    "4a2dbce82d7b4961996f69c8aad81664":{
      "scriptId":"u54"},
    "06cdfd5dd7d144759d3e720758d76913":{
      "scriptId":"u55"},
    "c312d0aad13f408b9bf4fc70754cce83":{
      "scriptId":"u56"},
    "dda1b31f934b423d897200d8a92cf97e":{
      "scriptId":"u57"},
    "82d72ab9044e4e24b5317243a9d2a730":{
      "scriptId":"u58"},
    "787c4b9e40cb4bbb966c00a86539a26e":{
      "scriptId":"u59"},
    "e0fe0c891f56412a94c981e619d729d9":{
      "scriptId":"u60"},
    "07db178763ec488fbb88dfda9d93427c":{
      "scriptId":"u61"},
    "ed44e94b54584dfab394aa2a12b8eb89":{
      "scriptId":"u62"},
    "7e998a82e35846faa58dc68cf65459e9":{
      "scriptId":"u63"},
    "774757e495c74613adaf17942514b029":{
      "scriptId":"u64"},
    "dee23cf9f8904e339fcefaab946c6c62":{
      "scriptId":"u65"},
    "dda17a519b2f40a587e882891c53fd34":{
      "scriptId":"u66"},
    "2fdc93ca094f4b7ab2356bbaf163c77b":{
      "scriptId":"u67"},
    "a597f8728f414feea489342dac3367ee":{
      "scriptId":"u68"},
    "cb9e8f642a724d21bf5f7a6997c0c6b2":{
      "scriptId":"u69"},
    "1ed45b3970cf4990af4fb20aabde02e7":{
      "scriptId":"u70"},
    "0572839a8a484f76a2e68df640ee4d4f":{
      "scriptId":"u71"},
    "f1dd187b2e1c495188a85f2a0b52e5fd":{
      "scriptId":"u72"},
    "02731b3162354b098c0f0cfd4f5e66ff":{
      "scriptId":"u73"},
    "824b27640b5b4f709431cd70861e512c":{
      "scriptId":"u74"},
    "6ba5e9e69f744e49a54057567ce95514":{
      "scriptId":"u75"},
    "22bb05691bb3451f9a382929f4c3904b":{
      "scriptId":"u76"},
    "c43b165ca7fc47b79b2a10c8d80bc461":{
      "scriptId":"u77"},
    "f6985bbd083c405b9d7b4fc24a12c574":{
      "scriptId":"u78",
      "bb20356460e0412d90c0916eb480f8c4":{
        "scriptId":"u79"},
      "b8218fa4a67e4e22be88537ce99d344e":{
        "scriptId":"u80"}}}});