$axure.loadCurrentPage({
  "url":"我的简历.html",
  "generationDate":new Date(1445572059448.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"58e25a184a214339b0f3194febc80287",
    "type":"Axure:Page",
    "name":"我的简历",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2ff5842ae0f34d76905be2a026a8b2ce",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"6da809df75bc435e9f8f821d61e292cb"},
{
          "id":"bddf2143870042ac82e0aa0bfdf7869c",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":80},
            "size":{
              "width":100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a01cf4bca4b24dc3981ce296dd0d04e7",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa275159d4e049469166440c94663f5d",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b3a8d5a968c141898be4a62c35025078",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"04e28250c79d4cf7b85c88cd04ea725c",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f50d203e280c42fa9a0a89e4434c9e4e",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ce519005950045c6b4e3cab0f4ae97a9",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"f50d203e280c42fa9a0a89e4434c9e4e"},
{
                  "id":"eaa65545375a4c768f4a37e71c3c4bbe",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5bbc480eceba48a5b0350e20735eb784",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的简历/u19.png",
                    "selected~":"images/我的简历/u19_selected.png"}},
{
                  "id":"7541901e8f2346ba8cca7bb22313c3ba",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"18d4a05d0cf6406699ac4407c92fb48d",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"cb3cdbf1cb95469598efb8bd39ca8597",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"18d4a05d0cf6406699ac4407c92fb48d"},
{
                  "id":"a6a1ec390f6547e89f53863e40c74f97",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8e0bc266cab5442fadc1d983d97ac5bb",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"eaa86767bba6471881c0df97eae58708",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"8e0bc266cab5442fadc1d983d97ac5bb"}],
              "buttonShapeId":"fa275159d4e049469166440c94663f5d"}]},
{
          "id":"12c9b3ecb1204e18bf07f53f1331fec5",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":200},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d89ebd6b16f4c64adba9478c9bf6a57",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "size":{
                  "width":104,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d4c5131cec2f45d6ac91bce99ac63b42",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":104,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"77e7c56074d24bac85d78533b53460fc",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":104,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d22b707c94c34c05b4cefbc982dbc394",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f00f933b857e46bbb11dffb73104f6cd",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":100,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e87edf8888b4435fb2a5b32ba0544feb",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":100,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"f00f933b857e46bbb11dffb73104f6cd"},
{
                  "id":"7f01dbb02b8c4eecb02a7b5dedbc70a3",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbb58d77637f490ab3b04ed045701092",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的简历/u19.png",
                    "selected~":"images/我的简历/u19_selected.png"}}],
              "buttonShapeId":"d4c5131cec2f45d6ac91bce99ac63b42"}]},
{
          "id":"da75bcffe45c410c8ef9de86a67d84cc",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":300},
            "size":{
              "width":80,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cff74a9644c249668d276331d6de9b75",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f6dfd4c58e924defb8c539c407d2751c",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"799a2738e27f458e8d7fd78427bccb26",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ac5d7da0cbe34f2aa7e533b96d27aa9e",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":35,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d1633ba7d79442e5beb59b09313ba78b",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":35,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"50046eef38bd413e8e15a8b0c44317ae",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":35,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"d1633ba7d79442e5beb59b09313ba78b"},
{
                  "id":"a0fd997fe7314f609c101af870378d34",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eb007c848f39437f9c1d81895478aea1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的简历/u19.png",
                    "selected~":"images/我的简历/u19_selected.png"}},
{
                  "id":"256eebfc3d4346cbb9d5c26f3e141771",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":35,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"723fda1eb2844f1fa0fbb7ba7cf6e417",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":35,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"60f965d0373b4ca5bc814b3b3bb75b4c",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":35,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"723fda1eb2844f1fa0fbb7ba7cf6e417"},
{
                  "id":"b92618cc205e441a93c75c169e81b3f5",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":35,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3697e65e51fd488684232bb09141e3b6",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":35,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8b3f9497bac44e9486782bc2110c3fcb",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":35,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"3697e65e51fd488684232bb09141e3b6"},
{
                  "id":"f0bfba0a803b4376894442b0a3e61dc2",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ddfd9b8189944a63895f23759c3a48a6",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"609e0ddc08ee44459c83e8ecd9e0ecb8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":100},
                            "size":{
                              "width":35,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"ddfd9b8189944a63895f23759c3a48a6"},
{
                  "id":"c0866c7ff5a145afad12f61dd122cdcb",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":80},
                    "size":{
                      "width":35,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c281d192c9cd4726b185f0dd8bb11b96",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":35,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1d8cf1050eec41b191134c32e295e1db",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":80},
                            "size":{
                              "width":35,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"c281d192c9cd4726b185f0dd8bb11b96"}],
              "buttonShapeId":"f6dfd4c58e924defb8c539c407d2751c"}]},
{
          "id":"9d01f0cdf7d94423b976dd1447bdd72e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":280,
              "y":80},
            "size":{
              "width":150,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9fd0afe87494125b08ae387c9117957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":280,
                  "y":80},
                "size":{
                  "width":150,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd54a377e4a742b4869da2e83ffba44e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":95},
            "size":{
              "width":140,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d91214d19087436c80abbeb565929738",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":95},
                "size":{
                  "width":140,
                  "height":115}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的简历/u64.png"}},
{
          "id":"ebfc80f052124b85af0b909251d0aecf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":113},
            "size":{
              "width":600,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcc561232a5f4eb7ac38de04eff60347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":113},
                "size":{
                  "width":600,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d941053993f9478eb58520a862e1970c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":270,
              "y":166},
            "size":{
              "width":150,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d56f1ae588841fda5c3135325c7cbf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":270,
                  "y":166},
                "size":{
                  "width":150,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f87a7a7e8bdc4d4a95dfc00812d4d321",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":270,
              "y":210},
            "size":{
              "width":600,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"703ef637b50245a0a5cfe76802a19703",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":270,
                  "y":210},
                "size":{
                  "width":600,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b69b69a9524142ae9032bd998e10bc90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":270,
              "y":260},
            "size":{
              "width":150,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99cbdea1e81b48f2909a52fd716344be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":270,
                  "y":260},
                "size":{
                  "width":150,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca3c1fabad644a2faf147fb85f69305f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":270,
              "y":293},
            "size":{
              "width":600,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fabce66ca7334125a3e91df582bd3cfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":270,
                  "y":293},
                "size":{
                  "width":600,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef9637fbc34043baa24f851fba79acc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":270,
              "y":350},
            "size":{
              "width":150,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e53d2da1a4bc40109818fba013dbaae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":270,
                  "y":350},
                "size":{
                  "width":150,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d3e8ea8353d43858c80432b7dff3625",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":270,
              "y":383},
            "size":{
              "width":600,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a59e041eb7946ec9fc2520b0c8912ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":270,
                  "y":383},
                "size":{
                  "width":600,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ed62b33d3814baa9ab59ebc8edff91b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":270,
              "y":460},
            "size":{
              "width":150,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce136e71829441a6b85d4f132ec9360f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":270,
                  "y":460},
                "size":{
                  "width":150,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5fcac19495c4046beb11b0a4334db24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":270,
              "y":493},
            "size":{
              "width":600,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"715b8692c470428fa112efb566ea1c05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":270,
                  "y":493},
                "size":{
                  "width":600,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f56851b319b9453285732448895ff823",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":590}},
          "adaptiveStyles":{
},
          "masterId":"8c817e2d85e64062b1846487b39e3063"}]}},
  "masters":{
    "6da809df75bc435e9f8f821d61e292cb":{
      "packageId":"6da809df75bc435e9f8f821d61e292cb",
      "type":"Axure:Master",
      "name":"页头",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"43c546d8915a4321b512e7f804b4b31e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a571167ed7224235a7198a8e4f110359",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u36.png"}},
{
            "id":"344dc1ea6f2b4a21a32f6157e7d79490",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":270,
                "y":0},
              "size":{
                "width":760,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4f095b0f21fd474a8ae783872f7d0aa0",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":760,
                    "height":50}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"15aa05ddc18e4905a7f91554614b1d1c",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":152,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62c4a66a4a6444fc8f9a66f70b72a3d7",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":152,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u40.png"}},
{
                    "id":"1e69bb34e50f41c2af0f4dc7999fe314",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":152,
                        "y":0},
                      "size":{
                        "width":152,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b4759a9621f1461f8979fd2955fb02f8",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":152,
                            "y":0},
                          "size":{
                            "width":152,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u40.png"}},
{
                    "id":"03a69b3e980849a6ad5ca77cf0a1a8ea",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":304,
                        "y":0},
                      "size":{
                        "width":151,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"34c59e722b7f4be6b3af43cb54a952b9",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":304,
                            "y":0},
                          "size":{
                            "width":151,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u44.png"}},
{
                    "id":"d95ac2c22e17453abbbc15cc449fdc87",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":690,
                        "y":0},
                      "size":{
                        "width":70,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"355cd0edf55240c4b0f391064d5ee483",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":690,
                            "y":0},
                          "size":{
                            "width":70,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u50.png"}},
{
                    "id":"4e46d7c13faf4dd998d38f2224d68a2c",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":628,
                        "y":0},
                      "size":{
                        "width":62,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"afc52319c03c4ca9acc862e980dc028f",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":628,
                            "y":0},
                          "size":{
                            "width":62,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u48.png"}},
{
                    "id":"a06282ff864e40c58625fdf5dd2852ff",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":455,
                        "y":0},
                      "size":{
                        "width":173,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"ed32fc37c7604284a760b3588a9f1915",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":455,
                            "y":0},
                          "size":{
                            "width":173,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u46.png"}}]}]}]}},
    "8c817e2d85e64062b1846487b39e3063":{
      "packageId":"8c817e2d85e64062b1846487b39e3063",
      "type":"Axure:Master",
      "name":"页脚",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"bb20356460e0412d90c0916eb480f8c4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF000000},
              "size":{
                "width":970,
                "height":96},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b8218fa4a67e4e22be88537ce99d344e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF000000},
                  "size":{
                    "width":970,
                    "height":96},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u137.png"}}]}}},
  "objectPaths":{
    "2ff5842ae0f34d76905be2a026a8b2ce":{
      "scriptId":"u0",
      "43c546d8915a4321b512e7f804b4b31e":{
        "scriptId":"u1"},
      "a571167ed7224235a7198a8e4f110359":{
        "scriptId":"u2"},
      "344dc1ea6f2b4a21a32f6157e7d79490":{
        "scriptId":"u3"},
      "4f095b0f21fd474a8ae783872f7d0aa0":{
        "scriptId":"u4"},
      "15aa05ddc18e4905a7f91554614b1d1c":{
        "scriptId":"u5"},
      "62c4a66a4a6444fc8f9a66f70b72a3d7":{
        "scriptId":"u6"},
      "1e69bb34e50f41c2af0f4dc7999fe314":{
        "scriptId":"u7"},
      "b4759a9621f1461f8979fd2955fb02f8":{
        "scriptId":"u8"},
      "03a69b3e980849a6ad5ca77cf0a1a8ea":{
        "scriptId":"u9"},
      "34c59e722b7f4be6b3af43cb54a952b9":{
        "scriptId":"u10"},
      "a06282ff864e40c58625fdf5dd2852ff":{
        "scriptId":"u11"},
      "ed32fc37c7604284a760b3588a9f1915":{
        "scriptId":"u12"},
      "4e46d7c13faf4dd998d38f2224d68a2c":{
        "scriptId":"u13"},
      "afc52319c03c4ca9acc862e980dc028f":{
        "scriptId":"u14"},
      "d95ac2c22e17453abbbc15cc449fdc87":{
        "scriptId":"u15"},
      "355cd0edf55240c4b0f391064d5ee483":{
        "scriptId":"u16"}},
    "bddf2143870042ac82e0aa0bfdf7869c":{
      "scriptId":"u17"},
    "a01cf4bca4b24dc3981ce296dd0d04e7":{
      "scriptId":"u18"},
    "eaa65545375a4c768f4a37e71c3c4bbe":{
      "scriptId":"u19"},
    "5bbc480eceba48a5b0350e20735eb784":{
      "scriptId":"u20"},
    "fa275159d4e049469166440c94663f5d":{
      "scriptId":"u21"},
    "b3a8d5a968c141898be4a62c35025078":{
      "scriptId":"u22"},
    "04e28250c79d4cf7b85c88cd04ea725c":{
      "scriptId":"u23"},
    "f50d203e280c42fa9a0a89e4434c9e4e":{
      "scriptId":"u24"},
    "ce519005950045c6b4e3cab0f4ae97a9":{
      "scriptId":"u25"},
    "7541901e8f2346ba8cca7bb22313c3ba":{
      "scriptId":"u26"},
    "18d4a05d0cf6406699ac4407c92fb48d":{
      "scriptId":"u27"},
    "cb3cdbf1cb95469598efb8bd39ca8597":{
      "scriptId":"u28"},
    "a6a1ec390f6547e89f53863e40c74f97":{
      "scriptId":"u29"},
    "8e0bc266cab5442fadc1d983d97ac5bb":{
      "scriptId":"u30"},
    "eaa86767bba6471881c0df97eae58708":{
      "scriptId":"u31"},
    "12c9b3ecb1204e18bf07f53f1331fec5":{
      "scriptId":"u32"},
    "9d89ebd6b16f4c64adba9478c9bf6a57":{
      "scriptId":"u33"},
    "7f01dbb02b8c4eecb02a7b5dedbc70a3":{
      "scriptId":"u34"},
    "dbb58d77637f490ab3b04ed045701092":{
      "scriptId":"u35"},
    "d4c5131cec2f45d6ac91bce99ac63b42":{
      "scriptId":"u36"},
    "77e7c56074d24bac85d78533b53460fc":{
      "scriptId":"u37"},
    "d22b707c94c34c05b4cefbc982dbc394":{
      "scriptId":"u38"},
    "f00f933b857e46bbb11dffb73104f6cd":{
      "scriptId":"u39"},
    "e87edf8888b4435fb2a5b32ba0544feb":{
      "scriptId":"u40"},
    "da75bcffe45c410c8ef9de86a67d84cc":{
      "scriptId":"u41"},
    "cff74a9644c249668d276331d6de9b75":{
      "scriptId":"u42"},
    "a0fd997fe7314f609c101af870378d34":{
      "scriptId":"u43"},
    "eb007c848f39437f9c1d81895478aea1":{
      "scriptId":"u44"},
    "f6dfd4c58e924defb8c539c407d2751c":{
      "scriptId":"u45"},
    "799a2738e27f458e8d7fd78427bccb26":{
      "scriptId":"u46"},
    "ac5d7da0cbe34f2aa7e533b96d27aa9e":{
      "scriptId":"u47"},
    "d1633ba7d79442e5beb59b09313ba78b":{
      "scriptId":"u48"},
    "50046eef38bd413e8e15a8b0c44317ae":{
      "scriptId":"u49"},
    "256eebfc3d4346cbb9d5c26f3e141771":{
      "scriptId":"u50"},
    "723fda1eb2844f1fa0fbb7ba7cf6e417":{
      "scriptId":"u51"},
    "60f965d0373b4ca5bc814b3b3bb75b4c":{
      "scriptId":"u52"},
    "b92618cc205e441a93c75c169e81b3f5":{
      "scriptId":"u53"},
    "3697e65e51fd488684232bb09141e3b6":{
      "scriptId":"u54"},
    "8b3f9497bac44e9486782bc2110c3fcb":{
      "scriptId":"u55"},
    "c0866c7ff5a145afad12f61dd122cdcb":{
      "scriptId":"u56"},
    "c281d192c9cd4726b185f0dd8bb11b96":{
      "scriptId":"u57"},
    "1d8cf1050eec41b191134c32e295e1db":{
      "scriptId":"u58"},
    "f0bfba0a803b4376894442b0a3e61dc2":{
      "scriptId":"u59"},
    "ddfd9b8189944a63895f23759c3a48a6":{
      "scriptId":"u60"},
    "609e0ddc08ee44459c83e8ecd9e0ecb8":{
      "scriptId":"u61"},
    "9d01f0cdf7d94423b976dd1447bdd72e":{
      "scriptId":"u62"},
    "a9fd0afe87494125b08ae387c9117957":{
      "scriptId":"u63"},
    "bd54a377e4a742b4869da2e83ffba44e":{
      "scriptId":"u64"},
    "d91214d19087436c80abbeb565929738":{
      "scriptId":"u65"},
    "ebfc80f052124b85af0b909251d0aecf":{
      "scriptId":"u66"},
    "bcc561232a5f4eb7ac38de04eff60347":{
      "scriptId":"u67"},
    "d941053993f9478eb58520a862e1970c":{
      "scriptId":"u68"},
    "6d56f1ae588841fda5c3135325c7cbf6":{
      "scriptId":"u69"},
    "f87a7a7e8bdc4d4a95dfc00812d4d321":{
      "scriptId":"u70"},
    "703ef637b50245a0a5cfe76802a19703":{
      "scriptId":"u71"},
    "b69b69a9524142ae9032bd998e10bc90":{
      "scriptId":"u72"},
    "99cbdea1e81b48f2909a52fd716344be":{
      "scriptId":"u73"},
    "ca3c1fabad644a2faf147fb85f69305f":{
      "scriptId":"u74"},
    "fabce66ca7334125a3e91df582bd3cfd":{
      "scriptId":"u75"},
    "ef9637fbc34043baa24f851fba79acc5":{
      "scriptId":"u76"},
    "e53d2da1a4bc40109818fba013dbaae9":{
      "scriptId":"u77"},
    "8d3e8ea8353d43858c80432b7dff3625":{
      "scriptId":"u78"},
    "2a59e041eb7946ec9fc2520b0c8912ad":{
      "scriptId":"u79"},
    "3ed62b33d3814baa9ab59ebc8edff91b":{
      "scriptId":"u80"},
    "ce136e71829441a6b85d4f132ec9360f":{
      "scriptId":"u81"},
    "d5fcac19495c4046beb11b0a4334db24":{
      "scriptId":"u82"},
    "715b8692c470428fa112efb566ea1c05":{
      "scriptId":"u83"},
    "f56851b319b9453285732448895ff823":{
      "scriptId":"u84",
      "bb20356460e0412d90c0916eb480f8c4":{
        "scriptId":"u85"},
      "b8218fa4a67e4e22be88537ce99d344e":{
        "scriptId":"u86"}}}});